describe('Walkthrough all state transitions', () => {
  it('From unknown state, when site accessed, should load Home page', () => {
    cy.visit('/')
    cy.contains('Home works!')
  })
  it('From home view state, when Products button clicked, should load Products List page', () => {
    cy.visit('/')
    cy.contains('Home works!')
    cy.get('button').contains('Products').click()
    cy.contains('List of Products')
    cy.contains('product_1')
    cy.contains('product_2')
  })
  it('From products list view state, when a product link clicked, should load product details of the product', () => {
    cy.visit('/')
    cy.contains('Home works!')
    cy.get('button').contains('Products').click()
    cy.contains('List of Products')
    cy.get('a').contains('product_1').click()
    cy.contains('Price: 11.11')
  })
  it('From products list view state, when Home button clicked, should load home page', () => {
    cy.visit('/')
    cy.contains('Home works!')
    cy.get('button').contains('Products').click()
    cy.contains('List of Products')
    cy.get('button').contains('Home').click()
    cy.contains('Home works!')
  })
  it('From product details view state, when Back to Products button clicked, should load Products List page', () => {
    cy.visit('/')
    cy.contains('Home works!')
    cy.get('button').contains('Products').click()
    cy.contains('List of Products')
    cy.get('a').contains('product_1').click()
    cy.get('button').contains('Back to Products').click()
    cy.contains('List of Products')
  })
  it('From product details view state, when Products menu button clicked, should load Products List page', () => {
    cy.visit('/')
    cy.contains('Home works!')
    cy.get('button').contains('Products').click()
    cy.contains('List of Products')
    cy.get('a').contains('product_1').click()
    cy.get('button').contains('Products').click()
    cy.contains('List of Products')
  })
  it('From product details view state, when Home menu button clicked, should load Home page', () => {
    cy.visit('/')
    cy.contains('Home works!')
    cy.get('button').contains('Products').click()
    cy.contains('List of Products')
    cy.get('a').contains('product_1').click()
    cy.get('button').contains('Home').click()
    cy.contains('Home works!')
  })
  it('Should load home page when unsupported path /bla is entered', () => {
    cy.visit('/bla')
    cy.contains('Home works!')
  })
  it('From products list view state, when bowser Back button clicked, hould stay in Products List', () => {
    cy.visit('/')
    cy.contains('Home works!')
    cy.get('button').contains('Products').click()
    cy.contains('List of Products')
    cy.go('back')
    cy.contains('List of Products')
  })
})

